### ISSUE TITLE
关于A1设备断开时，无法重启A2设备

### ISSUE THREAD

**Issue by PoWeR-Ding** [westarne/voicemeeter-auto-restart#1]
@westarne 你好
   很幸运能找到你这个小脚本，他解决了程序上自动重启音频引擎的不友好部分（程序自带的自动重启功能会无限自动循环重启，然而重启时候声音会断开1秒）。
   你这个小脚本，非常友好，非常棒。是先判断设备是否有连接上计算机再进行重启音频引擎功能。
   
   我在最近使用中发现脚本的bug：
1.A1通道 设备断开连接
2.A2通道 插上USB设备
此时我希望你的小脚本能自动重启A2通道音频引擎。但它没有正常工作，而是一直在判断和检查A1通道的设备（因为A1当前仍然断开连接的）

可以尽快检查修复这个bug吗？

**Comment by westarne** [comment]
Hello @PoWeR-Ding,

as far as I'm aware, device A1 has to be connected for any other device to function. So without a connected A1 nothing else will work as well. I'm currently still using Voicemeeter Potato 3.0.2.8, so I'm not sure whether this changed in a recent version.
So for my understanding, you need to use something in A1 that's always connected and then have variable devices in the other slots.

Regarding the actual restart: For me in a test without A1 connected but only A2 it didn't try to restart until I actually connected A1 again. So the script seems to work as intended for me. Maybe check that the Voicemeeter setting to auto restart for A1 is disabled (Menu > Auto Restart Audio Engine (A1 Device).

Best regards!

---
(Translated via Deepl)

你好 @PoWeR-Ding、

据我所知，必须连接设备 A1，其他设备才能工作。因此，如果没有连接的 A1，其他设备也无法工作。我目前仍在使用 Voicemeeter Potato 3.0.2.8，所以我不确定最近的版本是否有所改变。
因此，根据我的理解，您需要在 A1 中使用始终连接的设备，然后在其他插槽中使用可变设备。

关于实际重启： 对我来说，在没有连接 A1 而只有 A2 的测试中，直到我再次连接 A1 后才会尝试重启。因此，对我来说，脚本似乎是按预期工作的。也许可以检查一下 Voicemeeter 设置是否禁用了自动重启 A1（菜单 > 自动重启音频引擎（A1 设备））。

致以最崇高的敬意！

**Comment by PoWeR-Ding** [comment]
感谢您的回复。
是的，必须连接设备A1才能使任何其他设备发挥作用。我在昨晚也研究出来这个规则了。
所以我只能把A1设置为扬声器才能正常按照预期工作。（但它占用了我一条通道，= =! 气愤）
技术部 丁国辉
 <http://www.qtct.com.cn/ >
: Phone: +86.21.34241010
: Fax: +86.21.64699588
: Mobile: +86.13302302667
: Micro Blog：QTCT <http://weibo.com/QTCT >
: Email: ***@***.***
: Address: Room 201, Hongshan business building, 2121, Hongmei South Road, Shanghai，201108
: Web: http://www.QTCT.com.cn <http://www.qtct.com.cn/ >
------------------------------------------------------------------
发件人：Arne Westphal ***@***.***>
发送时间：2023年10月9日(星期一) 22:57
收件人：westarne/voicemeeter-auto-restart ***@***.***>
抄　送：丁国辉 ***@***.***>; Mention ***@***.***>
主　题：Re: [westarne/voicemeeter-auto-restart] 关于A1设备断开时，无法重启A2设备 (Issue #1)
Hello @PoWeR-Ding <https://github.com/PoWeR-Ding >,
as far as I'm aware, device A1 has to be connected for any other device to function. So without a connected A1 nothing else will work as well. I'm currently still using Voicemeeter Potato 3.0.2.8, so I'm not sure whether this changed in a recent version.
 So for my understanding, you need to use something in A1 that's always connected and then have variable devices in the other slots.
Regarding the actual restart: For me in a test without A1 connected but only A2 it didn't try to restart until I actually connected A1 again. So the script seems to work as intended for me. Maybe check that the Voicemeeter setting to auto restart for A1 is disabled (Menu > Auto Restart Audio Engine (A1 Device).
Best regards!
(Translated via Deepl)
你好 @PoWeR-Ding <https://github.com/PoWeR-Ding >、
据我所知，必须连接设备 A1，其他设备才能工作。因此，如果没有连接的 A1，其他设备也无法工作。我目前仍在使用 Voicemeeter Potato 3.0.2.8，所以我不确定最近的版本是否有所改变。
 因此，根据我的理解，您需要在 A1 中使用始终连接的设备，然后在其他插槽中使用可变设备。
关于实际重启： 对我来说，在没有连接 A1 而只有 A2 的测试中，直到我再次连接 A1 后才会尝试重启。因此，对我来说，脚本似乎是按预期工作的。也许可以检查一下 Voicemeeter 设置是否禁用了自动重启 A1（菜单 > 自动重启音频引擎（A1 设备））。
致以最崇高的敬意！

**Comment by PoWeR-Ding** [comment]
@westarne 


感谢您的回复。我目前用的是 Potato v3.0.2.2 。

是的，必须连接设备A1才能使任何其他设备发挥作用。我在昨晚也研究出来这个规则了。

所以我只能把A1设置为扬声器才能正常按照预期工作。（但它占用了我一条通道， 气愤 😡 ）
